-- Drops the legacy `org_product_config` table.
--
-- Context: the `featureStates` column stored an org-admin toggle for the
-- Writing product — the only feature that ever used this table. Writing
-- has been migrated into the canonical product-addon + capability model
-- (`product_addon_entitlements` in `org_entitlement_snapshot` for the
-- platform entitlement, `capabilities` in `org_product_policy` for the
-- org-admin toggle). With the call sites migrated to `can('product.writing')`
-- the table has no remaining readers or writers.
--
-- Verified empty on the target database before running.
DROP TABLE IF EXISTS org_product_config;
