/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appLayoutRouteRouteImport } from './routes/(app)/_layout/route'
import { Route as appLayoutIndexRouteImport } from './routes/(app)/_layout/index'
import { Route as appLayoutSplatRouteImport } from './routes/(app)/_layout/$'
import { Route as ApiAuthCallbackRouteRouteImport } from './routes/api/auth/callback/route'
import { Route as appLayoutWriterRouteRouteImport } from './routes/(app)/_layout/writer/route'
import { Route as appLayoutChatRouteRouteImport } from './routes/(app)/_layout/chat/route'

const appLayoutRouteRoute = appLayoutRouteRouteImport.update({
  id: '/(app)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutIndexRoute = appLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutSplatRoute = appLayoutSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const ApiAuthCallbackRouteRoute = ApiAuthCallbackRouteRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const appLayoutWriterRouteRoute = appLayoutWriterRouteRouteImport.update({
  id: '/writer',
  path: '/writer',
  getParentRoute: () => appLayoutRouteRoute,
} as any)
const appLayoutChatRouteRoute = appLayoutChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => appLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/chat': typeof appLayoutChatRouteRoute
  '/writer': typeof appLayoutWriterRouteRoute
  '/api/auth/callback': typeof ApiAuthCallbackRouteRoute
  '/$': typeof appLayoutSplatRoute
  '/': typeof appLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/chat': typeof appLayoutChatRouteRoute
  '/writer': typeof appLayoutWriterRouteRoute
  '/api/auth/callback': typeof ApiAuthCallbackRouteRoute
  '/$': typeof appLayoutSplatRoute
  '/': typeof appLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_layout': typeof appLayoutRouteRouteWithChildren
  '/(app)/_layout/chat': typeof appLayoutChatRouteRoute
  '/(app)/_layout/writer': typeof appLayoutWriterRouteRoute
  '/api/auth/callback': typeof ApiAuthCallbackRouteRoute
  '/(app)/_layout/$': typeof appLayoutSplatRoute
  '/(app)/_layout/': typeof appLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/chat' | '/writer' | '/api/auth/callback' | '/$' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/chat' | '/writer' | '/api/auth/callback' | '/$' | '/'
  id:
    | '__root__'
    | '/(app)/_layout'
    | '/(app)/_layout/chat'
    | '/(app)/_layout/writer'
    | '/api/auth/callback'
    | '/(app)/_layout/$'
    | '/(app)/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appLayoutRouteRoute: typeof appLayoutRouteRouteWithChildren
  ApiAuthCallbackRouteRoute: typeof ApiAuthCallbackRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)/_layout': {
      id: '/(app)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/': {
      id: '/(app)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appLayoutIndexRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/$': {
      id: '/(app)/_layout/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof appLayoutSplatRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_layout/writer': {
      id: '/(app)/_layout/writer'
      path: '/writer'
      fullPath: '/writer'
      preLoaderRoute: typeof appLayoutWriterRouteRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
    '/(app)/_layout/chat': {
      id: '/(app)/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof appLayoutChatRouteRouteImport
      parentRoute: typeof appLayoutRouteRoute
    }
  }
}

interface appLayoutRouteRouteChildren {
  appLayoutChatRouteRoute: typeof appLayoutChatRouteRoute
  appLayoutWriterRouteRoute: typeof appLayoutWriterRouteRoute
  appLayoutSplatRoute: typeof appLayoutSplatRoute
  appLayoutIndexRoute: typeof appLayoutIndexRoute
}

const appLayoutRouteRouteChildren: appLayoutRouteRouteChildren = {
  appLayoutChatRouteRoute: appLayoutChatRouteRoute,
  appLayoutWriterRouteRoute: appLayoutWriterRouteRoute,
  appLayoutSplatRoute: appLayoutSplatRoute,
  appLayoutIndexRoute: appLayoutIndexRoute,
}

const appLayoutRouteRouteWithChildren = appLayoutRouteRoute._addFileChildren(
  appLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appLayoutRouteRoute: appLayoutRouteRouteWithChildren,
  ApiAuthCallbackRouteRoute: ApiAuthCallbackRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
